### ISSUE TITLE
Exporter creates Update statements without PK-restriction

### ISSUE THREAD

**Issue by mschoenlaub** [resamsel/dbnavigator#10]
Even in the the simplest case, which means that I'm exporting only one table without references, the Exporter does not include a restriction in the update statement.

E.g. the given statement is:

```
update section set s_id = 3824, id = 131055131155, duration = 200, length = 600 [...] where ;
```

instead of 
```
update section set id = 131055131155, duration = 200, length = 600 [...] where s_id=3824;
```

**Comment by resamsel** [comment]
@mschoenlaub, please add the command line to reproduce the issue (with user@host hidden).

**Comment by resamsel** [comment]
@mschoenlaub: there was probably an error with the database, i can't reproduce that issue at all.
