### ISSUE TITLE
Improve error messages if no database connector is configured

### ISSUE THREAD

**Issue by hs-alexander** [resamsel/dbnavigator#12]
Steps for reproduction:
* Install on a system without python database connector(s) but existing postgres connection configuration (.pgpass)
* execute dbexport user@connection/database/table
* Error message is "Specify the complete URI to a table"

Error message should be: "It was not possible to connect to the database. If the connection is not among the following connections, please install connector (see [location of description]):
[list of connection]

**Comment by resamsel** [comment]
Will now display **Connection "{0}" was not found** instead of of the generic message above.
